import csv
import os

rows = [
    # Chapter 1 - 操作系统概述
    {
        "node_id": 723,
        "name": "1 操作系统概述",
        "level": 2,
        "definition": "操作系统是管理计算机硬件与软件资源的系统软件，是用户与计算机硬件之间的接口。",
        "core_elements": "硬件管理 | 软件服务 | 用户接口 | 资源分配",
        "key_terms": "操作系统 | 系统软件 | 接口",
        "formulas": "[]",
        "common_mistakes": "将操作系统等同于应用软件 | 忽略操作系统对硬件的直接管理作用",
        "scope_boundary": "不涉及具体操作系统内部实现细节，仅做宏观概述",
        "prerequisites_desc": "具备计算机组成原理和程序设计的基础知识。"
    },
    {
        "node_id": 724,
        "name": "1.1 操作系统的基本概念",
        "level": 3,
        "definition": "从功能、特征和目标等角度全面理解操作系统的本质属性和存在意义。",
        "core_elements": "概念定义 | 功能目标 | 基本特征",
        "key_terms": "操作系统 | 功能 | 特征",
        "formulas": "[]",
        "common_mistakes": "混淆操作系统的功能和目标 | 将特征等同于功能",
        "scope_boundary": "不深入讨论具体操作系统的设计与实现",
        "prerequisites_desc": "需先了解操作系统的基本定义和作用。"
    },
    {
        "node_id": 725,
        "name": "1.1.1 操作系统的概念",
        "level": 4,
        "definition": "操作系统是控制和管理计算机系统内各种硬件和软件资源、合理组织计算机工作流程的系统软件。",
        "core_elements": "资源管理器 | 硬件抽象 | 用户接口 | 程序执行环境",
        "key_terms": "操作系统 | 系统软件 | 资源管理",
        "formulas": "[]",
        "common_mistakes": "将操作系统视为应用软件 | 认为操作系统仅是用户界面",
        "scope_boundary": "不涉及操作系统内核的具体实现机制",
        "prerequisites_desc": "需了解计算机硬件组成和软件分类。"
    },
    {
        "node_id": 726,
        "name": "1.1.2 操作系统的功能和目标",
        "level": 4,
        "definition": "操作系统的核心功能包括处理器管理、存储器管理、设备管理和文件管理，目标是方便、高效和安全。",
        "core_elements": "处理器管理 | 存储器管理 | 设备管理 | 文件管理 | 系统安全",
        "key_terms": "功能 | 目标 | 方便性 | 高效性 | 安全性",
        "formulas": "[]",
        "common_mistakes": "将功能与目标混淆 | 忽略安全目标的重要性",
        "scope_boundary": "不深入各管理模块的具体算法和数据结构",
        "prerequisites_desc": "需理解操作系统的概念和计算机系统结构。"
    },
    {
        "node_id": 727,
        "name": "1.1.3 操作系统的特征",
        "level": 4,
        "definition": "操作系统具有并发、共享、虚拟和异步四个基本特征，其中并发和共享是基础特征。",
        "core_elements": "并发性 | 共享性 | 虚拟性 | 异步性",
        "key_terms": "并发 | 共享 | 虚拟 | 异步",
        "formulas": "[]",
        "common_mistakes": "将并发等同于并行 | 忽略异步性的含义 | 混淆虚拟与模拟",
        "scope_boundary": "不涉及各特征的具体实现技术",
        "prerequisites_desc": "需理解操作系统的基本概念和功能。"
    },
    {
        "node_id": 728,
        "name": "1.2 操作系统发展历程",
        "level": 3,
        "definition": "操作系统从手工操作到批处理、分时、实时、网络和分布式系统的演进过程。",
        "core_elements": "手工操作阶段 | 批处理阶段 | 分时系统 | 实时系统 | 网络与分布式系统",
        "key_terms": "发展历程 | 批处理 | 分时 | 实时",
        "formulas": "[]",
        "common_mistakes": "混淆各阶段的技术特征 | 忽略各阶段的驱动因素",
        "scope_boundary": "不深入分析各阶段的详细技术实现",
        "prerequisites_desc": "需了解计算机硬件的发展历史。"
    },
    {
        "node_id": 729,
        "name": "1.2.1 手工操作阶段（未配置操作系统）",
        "level": 4,
        "definition": "早期计算机通过穿孔纸带手工输入程序，CPU大量时间处于空闲状态，效率极低。",
        "core_elements": "穿孔纸带 | 手工装卸 | CPU空闲 | 无操作系统",
        "key_terms": "手工操作 | 穿孔纸带 | 作业",
        "formulas": "[]",
        "common_mistakes": "认为手工操作阶段已有操作系统 | 高估此阶段的自动化程度",
        "scope_boundary": "不讨论手工操作的具体操作流程细节",
        "prerequisites_desc": "需了解早期计算机的基本工作方式。"
    },
    {
        "node_id": 730,
        "name": "1.2.2 批处理阶段（操作系统开始出现）",
        "level": 4,
        "definition": "将多个作业成批提交计算机，由监控程序自动调度执行，分为单道和多道批处理系统。",
        "core_elements": "监控程序 | 作业调度 | 单道批处理 | 多道批处理",
        "key_terms": "批处理 | 监控程序 | 作业 | 多道程序设计",
        "formulas": "[]",
        "common_mistakes": "混淆单道和多道批处理的区别 | 认为批处理就是分时系统",
        "scope_boundary": "不深入分析调度算法的具体实现",
        "prerequisites_desc": "需理解手工操作阶段的局限性。"
    },
    {
        "node_id": 731,
        "name": "1.2.3 分时操作系统",
        "level": 4,
        "definition": "采用时间片轮转方式为多个用户提供交互式服务，使用户感觉独占计算机。",
        "core_elements": "时间片轮转 | 多路性 | 交互性 | 独占感",
        "key_terms": "分时系统 | 时间片 | 交互性 | 多路性",
        "formulas": "[]",
        "common_mistakes": "将分时等同于实时 | 认为分时系统无并发",
        "scope_boundary": "不讨论时间片长度的优化问题",
        "prerequisites_desc": "需理解批处理系统的特点和不足。"
    },
    {
        "node_id": 732,
        "name": "1.2.4 实时操作系统",
        "level": 4,
        "definition": "在严格时间限制内响应外部事件并完成处理任务的系统，分为硬实时和软实时。",
        "core_elements": "严格时限 | 快速响应 | 硬实时 | 软实时",
        "key_terms": "实时系统 | 硬实时 | 软实时 | 截止时间",
        "formulas": "[]",
        "common_mistakes": "混淆硬实时和软实时的定义 | 将实时等同于快速",
        "scope_boundary": "不讨论实时系统的具体调度算法",
        "prerequisites_desc": "需了解分时系统的工作原理。"
    },
    {
        "node_id": 733,
        "name": "1.2.5 网络操作系统和分布式系统",
        "level": 4,
        "definition": "网络操作系统提供网络管理和资源共享，分布式系统将任务分布到多台计算机协同完成。",
        "core_elements": "网络管理 | 资源共享 | 任务分布 | 协同计算",
        "key_terms": "网络操作系统 | 分布式系统 | 透明性",
        "formulas": "[]",
        "common_mistakes": "将网络操作系统等同于分布式系统 | 忽略分布式系统的透明性",
        "scope_boundary": "不讨论网络协议和分布式算法的具体实现",
        "prerequisites_desc": "需了解计算机网络的基本概念。"
    },
    {
        "node_id": 734,
        "name": "1.2.6 微机操作系统",
        "level": 4,
        "definition": "面向个人计算机的操作系统，从单用户单任务发展到多用户多任务，代表有DOS、Windows、Linux等。",
        "core_elements": "单用户单任务 | 多用户多任务 | 图形界面 | 多媒体支持",
        "key_terms": "微机操作系统 | DOS | Windows | Linux",
        "formulas": "[]",
        "common_mistakes": "认为微机操作系统就是个人电脑操作系统 | 忽略其发展演变过程",
        "scope_boundary": "不比较各微机操作系统的优劣",
        "prerequisites_desc": "需了解操作系统的基本发展历程。"
    },
    {
        "node_id": 735,
        "name": "1.3 操作系统的运行环境",
        "level": 3,
        "definition": "操作系统运行所需的硬件支持和软件环境，包括内核结构、处理机模式和中断机制。",
        "core_elements": "内核结构 | 处理机模式 | 中断机制 | 系统调用",
        "key_terms": "运行环境 | 内核 | 中断 | 系统调用",
        "formulas": "[]",
        "common_mistakes": "混淆内核态和用户态的区别 | 忽略中断的重要性",
        "scope_boundary": "不深入讨论内核的具体设计和实现",
        "prerequisites_desc": "需理解操作系统的基本概念和功能。"
    },
    {
        "node_id": 736,
        "name": "1.3.1 操作系统内核",
        "level": 4,
        "definition": "操作系统内核是操作系统最基本的部分，管理系统的事务处理、中断、异常和系统调用等。",
        "core_elements": "事务处理 | 中断管理 | 异常处理 | 系统调用",
        "key_terms": "内核 | 微内核 | 宏内核",
        "formulas": "[]",
        "common_mistakes": "将内核等同于操作系统 | 混淆微内核和宏内核",
        "scope_boundary": "不讨论不同内核架构的优劣比较",
        "prerequisites_desc": "需了解操作系统的基本组成和运行环境。"
    },
    {
        "node_id": 737,
        "name": "1.3.2 处理机的双重工作模式",
        "level": 4,
        "definition": "处理机分为用户态和内核态两种模式，用户态程序不能直接访问内核态资源，需通过系统调用。",
        "core_elements": "用户态 | 内核态 | 模式切换 | 特权指令",
        "key_terms": "用户态 | 内核态 | 模式位 | 特权指令",
        "formulas": "[]",
        "common_mistakes": "认为用户态程序可直接执行特权指令 | 忽略模式切换的开销",
        "scope_boundary": "不讨论模式切换的具体实现细节",
        "prerequisites_desc": "需了解操作系统内核和处理机的工作方式。"
    },
    {
        "node_id": 738,
        "name": "1.3.3 中断和异常的概念",
        "level": 4,
        "definition": "中断是由外部设备引起的异步事件，异常是CPU执行指令时产生的同步事件，两者都是操作系统获得控制权的手段。",
        "core_elements": "中断 | 异步事件 | 同步事件 | 控制权转移",
        "key_terms": "中断 | 异常 | 中断向量 | 中断服务程序",
        "formulas": "[]",
        "common_mistakes": "混淆中断和异常的区别 | 认为中断只能由硬件引起",
        "scope_boundary": "不讨论中断控制器的具体硬件实现",
        "prerequisites_desc": "需了解处理机的工作模式和计算机组成原理。"
    },
    {
        "node_id": 739,
        "name": "1.3.4 系统调用",
        "level": 4,
        "definition": "操作系统提供给应用程序的接口，用户程序通过系统调用请求操作系统服务，实现从用户态到内核态的切换。",
        "core_elements": "应用程序接口 | 服务请求 | 态切换 | 功能封装",
        "key_terms": "系统调用 | API | 用户态 | 内核态",
        "formulas": "[]",
        "common_mistakes": "将系统调用等同于普通函数调用 | 忽略系统调用的态切换开销",
        "scope_boundary": "不讨论具体系统调用的实现细节",
        "prerequisites_desc": "需理解处理机的工作模式和中断的概念。"
    },
    {
        "node_id": 740,
        "name": "1.4 操作系统结构",
        "level": 3,
        "definition": "操作系统的整体架构设计方式，包括模块化、分层、微内核和外核等结构。",
        "core_elements": "模块化结构 | 分层结构 | 微内核结构 | 外核结构",
        "key_terms": "模块化 | 分层 | 微内核 | 外核",
        "formulas": "[]",
        "common_mistakes": "混淆不同操作系统结构的特点 | 认为微内核比宏内核更优",
        "scope_boundary": "不深入讨论各结构的具体设计和实现",
        "prerequisites_desc": "需了解操作系统内核的基本概念。"
    },
    {
        "node_id": 741,
        "name": "1.5 操作系统引导",
        "level": 3,
        "definition": "计算机加电后操作系统从存储设备加载到内存并开始执行的过程，包括BIOS自检和引导程序加载。",
        "core_elements": "BIOS自检 | 引导程序 | 分区表 | 操作系统加载",
        "key_terms": "引导 | BIOS | MBR | GRUB",
        "formulas": "[]",
        "common_mistakes": "将BIOS等同于操作系统 | 忽略引导程序的作用",
        "scope_boundary": "不讨论具体BIOS和引导程序的实现",
        "prerequisites_desc": "需了解计算机硬件启动过程。"
    },
    {
        "node_id": 742,
        "name": "1.6 虚拟机",
        "level": 3,
        "definition": "通过软件模拟完整计算机硬件环境，使一台物理机可同时运行多个操作系统实例的技术。",
        "core_elements": "软件模拟 | 硬件抽象 | 多实例运行 | 资源隔离",
        "key_terms": "虚拟机 | Hypervisor | 虚拟化",
        "formulas": "[]",
        "common_mistakes": "将虚拟机等同于模拟器 | 忽略虚拟化的性能开销",
        "scope_boundary": "不讨论虚拟机的具体实现技术",
        "prerequisites_desc": "需了解操作系统的基本概念和计算机硬件。"
    },
    {
        "node_id": 743,
        "name": "1.6.1 虚拟机的基本概念",
        "level": 4,
        "definition": "虚拟机是一种软件实现的计算机，它在物理计算机之上模拟出完整的硬件环境供操作系统运行。",
        "core_elements": "虚拟硬件 | Guest OS | Host OS | 资源共享",
        "key_terms": "虚拟机 | Hypervisor | 虚拟化技术",
        "formulas": "[]",
        "common_mistakes": "混淆Type-1和Type-2虚拟机 | 认为虚拟机无性能损失",
        "scope_boundary": "不讨论虚拟机的性能优化和管理工具",
        "prerequisites_desc": "需理解操作系统的基本概念和虚拟化技术。"
    },

    # Chapter 2 - 进程管理
    {
        "node_id": 744,
        "name": "2 进程管理",
        "level": 2,
        "definition": "操作系统对进程的创建、调度、同步、通信和撤销等全生命周期的管理。",
        "core_elements": "进程概念 | CPU调度 | 同步互斥 | 死锁处理",
        "key_terms": "进程 | 线程 | 调度 | 同步 | 死锁",
        "formulas": "[]",
        "common_mistakes": "混淆进程和程序的概念 | 忽略进程同步的重要性",
        "scope_boundary": "仅讨论单处理器系统的进程管理",
        "prerequisites_desc": "需理解操作系统的基本概念和处理机的工作方式。"
    },
    {
        "node_id": 745,
        "name": "2.1 进程与线程简介",
        "level": 3,
        "definition": "进程是程序的一次执行过程，是资源分配的基本单位；线程是进程中的执行单元，是CPU调度的基本单位。",
        "core_elements": "进程定义 | 线程定义 | 进程组成 | 进程状态",
        "key_terms": "进程 | 线程 | 程序 | 执行流",
        "formulas": "[]",
        "common_mistakes": "将进程等同于程序 | 混淆进程和线程的调度单位",
        "scope_boundary": "不深入讨论进程调度算法和同步机制",
        "prerequisites_desc": "需了解操作系统的基本概念和程序执行原理。"
    },
    {
        "node_id": 746,
        "name": "2.1.1 进程的概念和特征",
        "level": 4,
        "definition": "进程是程序在处理器上的一次执行过程，具有动态性、并发性、独立性和异步性等特征。",
        "core_elements": "动态性 | 并发性 | 独立性 | 异步性 | 结构性",
        "key_terms": "进程 | PCB | 动态性 | 并发性",
        "formulas": "[]",
        "common_mistakes": "认为进程是静态的程序代码 | 忽略进程的动态特征",
        "scope_boundary": "不讨论进程控制块的具体结构",
        "prerequisites_desc": "需理解程序的执行过程和操作系统的并发特性。"
    },
    {
        "node_id": 747,
        "name": "2.1.2 进程的组成",
        "level": 4,
        "definition": "进程由程序段、数据段和进程控制块(PCB)三部分组成，PCB是进程存在的唯一标志。",
        "core_elements": "程序段 | 数据段 | 进程控制块(PCB) | 进程标识符",
        "key_terms": "PCB | 程序段 | 数据段 | 进程标识符",
        "formulas": "[]",
        "common_mistakes": "忽略PCB的重要性 | 认为进程仅由程序组成",
        "scope_boundary": "不讨论PCB的具体数据结构设计",
        "prerequisites_desc": "需了解进程的基本概念和程序的组成。"
    },
    {
        "node_id": 748,
        "name": "2.1.3 进程的内存映像",
        "level": 4,
        "definition": "进程在内存中的布局，从低地址到高地址依次为代码段、数据段、堆和栈。",
        "core_elements": "代码段 | 数据段 | 堆 | 栈 | 内存布局",
        "key_terms": "内存映像 | 代码段 | 数据段 | 堆 | 栈",
        "formulas": "[]",
        "common_mistakes": "混淆堆和栈的增长方向 | 忽略内存对齐的要求",
        "scope_boundary": "不讨论内存管理的具体实现机制",
        "prerequisites_desc": "需了解进程的基本组成和计算机内存结构。"
    },
    {
        "node_id": 749,
        "name": "2.1.4 进程的状态与转换",
        "level": 4,
        "definition": "进程在生命周期中经历创建、就绪、运行、阻塞和终止五种基本状态，并按一定规则转换。",
        "core_elements": "创建态 | 就绪态 | 运行态 | 阻塞态 | 终止态",
        "key_terms": "进程状态 | 状态转换 | 就绪队列 | 阻塞队列",
        "formulas": "[]",
        "common_mistakes": "混淆阻塞态和就绪态 | 认为进程只能在就绪和运行间转换",
        "scope_boundary": "不讨论状态转换的具体实现算法",
        "prerequisites_desc": "需了解进程的基本概念和CPU调度。"
    },
    {
        "node_id": 750,
        "name": "2.1.5 进程控制",
        "level": 4,
        "definition": "操作系统对进程生命周期的管理，包括进程创建、终止、阻塞和唤醒等操作。",
        "core_elements": "进程创建 | 进程终止 | 进程阻塞 | 进程唤醒",
        "key_terms": "进程控制 | fork | exit | wait",
        "formulas": "[]",
        "common_mistakes": "忽略进程终止时的资源回收 | 混淆阻塞和挂起的区别",
        "scope_boundary": "不讨论进程控制的具体系统调用实现",
        "prerequisites_desc": "需了解进程的状态和组成。"
    },
    {
        "node_id": 751,
        "name": "2.1.6 进程的通信",
        "level": 4,
        "definition": "进程间交换数据和信息的方式，包括共享内存、消息传递和管道通信等机制。",
        "core_elements": "共享内存 | 消息传递 | 管道 | 信号量",
        "key_terms": "进程通信 | 共享内存 | 消息传递 | 管道",
        "formulas": "[]",
        "common_mistakes": "混淆共享内存和消息传递的特点 | 认为管道只能用于父子进程",
        "scope_boundary": "不讨论具体通信机制的实现细节",
        "prerequisites_desc": "需了解进程的基本概念和内存管理。"
    },
    {
        "node_id": 752,
        "name": "2.1.7 线程和多线程模型",
        "level": 4,
        "definition": "线程是进程内的轻量级执行单元，多线程模型包括多对一、一对一和多对多三种类型。",
        "core_elements": "轻量级执行单元 | 多对一模型 | 一对一模型 | 多对多模型",
        "key_terms": "线程 | 多线程 | 用户级线程 | 内核级线程",
        "formulas": "[]",
        "common_mistakes": "混淆用户级线程和内核级线程 | 认为多线程一定比单线程快",
        "scope_boundary": "不讨论线程同步和通信的具体机制",
        "prerequisites_desc": "需了解进程的基本概念和组成。"
    },
    {
        "node_id": 753,
        "name": "2.2 CPU调度",
        "level": 3,
        "definition": "操作系统按照一定策略从就绪队列中选择一个进程分配CPU资源的过程。",
        "core_elements": "调度概念 | 调度层次 | 调度算法 | 调度目标",
        "key_terms": "CPU调度 | 就绪队列 | 调度算法",
        "formulas": "[]",
        "common_mistakes": "混淆不同调度层次的区别 | 忽略调度目标的多样性",
        "scope_boundary": "不讨论具体调度算法的实现细节",
        "prerequisites_desc": "需了解进程的状态和转换。"
    },
    {
        "node_id": 754,
        "name": "2.2.1 调度的概念",
        "level": 4,
        "definition": "调度是从就绪进程队列中按照一定算法选择一个进程并将CPU分配给它运行的过程。",
        "core_elements": "选择进程 | 分配CPU | 就绪队列 | 调度算法",
        "key_terms": "调度 | 进程调度 | 就绪队列",
        "formulas": "[]",
        "common_mistakes": "将调度等同于进程切换 | 忽略调度的开销",
        "scope_boundary": "不讨论具体调度算法的比较",
        "prerequisites_desc": "需了解进程的状态和转换。"
    },
    {
        "node_id": 755,
        "name": "2.2.2 进程调度",
        "level": 4,
        "definition": "决定哪个就绪进程获得CPU使用权的过程，分为抢占式和非抢占式两种方式。",
        "core_elements": "抢占式调度 | 非抢占式调度 | 调度时机 | 调度策略",
        "key_terms": "抢占式 | 非抢占式 | 调度时机",
        "formulas": "[]",
        "common_mistakes": "混淆抢占式和非抢占式的区别 | 忽略调度时机的选择",
        "scope_boundary": "不讨论具体调度算法的实现",
        "prerequisites_desc": "需理解进程调度的基本概念。"
    },
    {
        "node_id": 756,
        "name": "2.2.3 调度的目标",
        "level": 4,
        "definition": "CPU调度需要实现的目标包括CPU利用率高、系统吞吐量大、周转时间短、响应时间快和公平性等。",
        "core_elements": "CPU利用率 | 系统吞吐量 | 周转时间 | 响应时间 | 公平性",
        "key_terms": "CPU利用率 | 吞吐量 | 周转时间 | 响应时间",
        "formulas": "周转时间 = 完成时间 - 提交时间 | 带权周转时间 = 周转时间 / 执行时间",
        "common_mistakes": "忽略调度目标间的冲突 | 只关注单一目标",
        "scope_boundary": "不讨论目标之间的权衡方法",
        "prerequisites_desc": "需了解进程调度的基本概念和目标。"
    },
    {
        "node_id": 757,
        "name": "2.2.4 进程切换",
        "level": 4,
        "definition": "当CPU从一个进程切换到另一个进程时，需要保存当前进程的上下文并恢复新进程的上下文。",
        "core_elements": "上下文保存 | 上下文恢复 | 进程控制块 | 模式切换",
        "key_terms": "进程切换 | 上下文切换 | PCB",
        "formulas": "[]",
        "common_mistakes": "将进程切换等同于模式切换 | 忽略切换开销",
        "scope_boundary": "不讨论上下文切换的硬件支持",
        "prerequisites_desc": "需了解进程的组成和处理机的工作模式。"
    },
    {
        "node_id": 758,
        "name": "2.2.5 CPU调度算法",
        "level": 4,
        "definition": "常见的调度算法包括先来先服务、短作业优先、优先级调度、时间片轮转和多级反馈队列等。",
        "core_elements": "FCFS | SJF | 优先级调度 | 时间片轮转 | 多级反馈队列",
        "key_terms": "FCFS | SJF | 优先级调度 | 时间片轮转",
        "formulas": "平均周转时间 = Σ周转时间 / 进程数 | 平均等待时间 = Σ等待时间 / 进程数",
        "common_mistakes": "混淆不同调度算法的特点 | 忽略算法的饥饿问题",
        "scope_boundary": "不讨论算法的具体实现代码",
        "prerequisites_desc": "需了解CPU调度的目标和进程调度方式。"
    },
    {
        "node_id": 759,
        "name": "2.2.6 多处理机调度",
        "level": 3,
        "definition": "在多处理器环境下，进程如何在多个CPU之间分配和调度的问题，包括对称和非对称多处理。",
        "core_elements": "对称多处理 | 非对称多处理 | 负载均衡 | 处理器亲和性",
        "key_terms": "多处理机 | 负载均衡 | 处理器亲和性",
        "formulas": "[]",
        "common_mistakes": "忽略负载均衡的重要性 | 混淆对称和非对称多处理",
        "scope_boundary": "不讨论多处理器调度的具体算法实现",
        "prerequisites_desc": "需了解单处理器CPU调度算法。"
    },
    {
        "node_id": 760,
        "name": "2.3 同步与互斥",
        "level": 3,
        "definition": "协调多个进程对共享资源的访问，保证进程间正确的执行顺序和数据一致性。",
        "core_elements": "同步 | 互斥 | 临界区 | 共享资源",
        "key_terms": "同步 | 互斥 | 临界区 | 竞争条件",
        "formulas": "[]",
        "common_mistakes": "混淆同步和互斥的概念 | 忽略竞争条件的危害",
        "scope_boundary": "不讨论同步机制的具体实现细节",
        "prerequisites_desc": "需了解进程的基本概念和通信方式。"
    },
    {
        "node_id": 761,
        "name": "2.3.1 同步与互斥的基本概念",
        "level": 4,
        "definition": "互斥指多个进程不能同时使用同一资源，同步指进程间按预定顺序协调执行。",
        "core_elements": "互斥关系 | 同步关系 | 临界资源 | 临界区",
        "key_terms": "互斥 | 同步 | 临界资源 | 临界区",
        "formulas": "[]",
        "common_mistakes": "将同步和互斥混为一谈 | 忽略临界区的定义",
        "scope_boundary": "不讨论同步机制的具体实现",
        "prerequisites_desc": "需了解进程的基本概念和并发执行的特点。"
    },
    {
        "node_id": 762,
        "name": "2.3.2 实现临界区互斥的基本方法",
        "level": 4,
        "definition": "包括软件方法（如Peterson算法）和硬件方法（如中断禁用、硬件指令）实现临界区互斥。",
        "core_elements": "软件方法 | 硬件方法 | Peterson算法 | 中断禁用 | Test-and-Set",
        "key_terms": "Peterson算法 | Test-and-Set | Compare-and-Swap",
        "formulas": "[]",
        "common_mistakes": "认为中断禁用适用于多处理器环境 | 忽略Peterson算法的局限性",
        "scope_boundary": "不讨论高级同步机制的实现",
        "prerequisites_desc": "需理解同步与互斥的基本概念。"
    },
    {
        "node_id": 763,
        "name": "2.3.3 互斥锁",
        "level": 4,
        "definition": "互斥锁是最简单的同步工具，通过lock和unlock操作保证同一时刻只有一个进程进入临界区。",
        "core_elements": "lock操作 | unlock操作 | 忙等待 | 自旋锁",
        "key_terms": "互斥锁 | 自旋锁 | 忙等待",
        "formulas": "[]",
        "common_mistakes": "忽略忙等待的CPU浪费 | 将互斥锁等同于信号量",
        "scope_boundary": "不讨论互斥锁的底层硬件实现",
        "prerequisites_desc": "需理解临界区和互斥的概念。"
    },
    {
        "node_id": 764,
        "name": "2.3.4 信号量",
        "level": 4,
        "definition": "信号量是一种用于进程同步和互斥的整型变量，通过P(wait)和V(signal)操作实现。",
        "core_elements": "整型信号量 | P操作 | V操作 | 队列机制",
        "key_terms": "信号量 | P操作 | V操作 | wait | signal",
        "formulas": "P(S): S=S-1; if S<0 then block | V(S): S=S+1; if S<=0 then wakeup",
        "common_mistakes": "P和V操作顺序错误导致死锁 | 忽略信号量的初值设置",
        "scope_boundary": "不讨论信号量在具体操作系统中的实现",
        "prerequisites_desc": "需了解互斥锁和进程同步的基本概念。"
    },
    {
        "node_id": 765,
        "name": "2.3.5 经典同步问题",
        "level": 4,
        "definition": "包括生产者-消费者、读者-写者、哲学家就餐等经典问题，是同步机制的典型应用。",
        "core_elements": "生产者-消费者 | 读者-写者 | 哲学家就餐 | 睡眠理发师",
        "key_terms": "生产者-消费者 | 读者-写者 | 哲学家就餐",
        "formulas": "[]",
        "common_mistakes": "生产者-消费者中缓冲区满时的处理 | 读者-写者中写者饥饿问题",
        "scope_boundary": "不讨论问题的变体和优化解法",
        "prerequisites_desc": "需掌握信号量和P/V操作的使用。"
    },
    {
        "node_id": 766,
        "name": "2.3.6 管程",
        "level": 4,
        "definition": "管程是将共享数据和对数据的操作封装在一起的同步机制，内部只能有一个进程执行。",
        "core_elements": "封装数据 | 条件变量 | 进程互斥 | 条件等待",
        "key_terms": "管程 | 条件变量 | enter | leave",
        "formulas": "[]",
        "common_mistakes": "将管程等同于进程 | 忽略条件变量的使用",
        "scope_boundary": "不讨论管程的编程语言实现差异",
        "prerequisites_desc": "需理解信号量和进程同步的基本原理。"
    },
    {
        "node_id": 767,
        "name": "2.4 死锁",
        "level": 3,
        "definition": "多个进程因竞争资源而造成互相等待的僵局状态，若无外力作用则无法继续执行。",
        "core_elements": "死锁定义 | 产生条件 | 预防策略 | 避免算法 | 检测解除",
        "key_terms": "死锁 | 互斥 | 占有等待 | 不可剥夺 | 循环等待",
        "formulas": "[]",
        "common_mistakes": "混淆死锁预防和死锁避免 | 认为死锁只在多处理器环境出现",
        "scope_boundary": "不讨论死锁的分布式处理",
        "prerequisites_desc": "需了解进程同步和资源分配的基本概念。"
    },
    {
        "node_id": 768,
        "name": "2.4.1 死锁的概念",
        "level": 4,
        "definition": "死锁是指两个或多个进程因竞争资源而相互等待，且无法自行解除的状态。",
        "core_elements": "互斥条件 | 占有并等待 | 不可剥夺 | 循环等待",
        "key_terms": "死锁 | 资源分配图 | 死锁定理",
        "formulas": "死锁必要条件：互斥 + 占有等待 + 不可剥夺 + 循环等待",
        "common_mistakes": "认为死锁只在特殊条件下发生 | 忽略死锁的四个必要条件",
        "scope_boundary": "不讨论死锁的检测算法细节",
        "prerequisites_desc": "需了解进程同步和资源分配的概念。"
    },
    {
        "node_id": 769,
        "name": "2.4.2 死锁预防",
        "level": 4,
        "definition": "通过破坏死锁的四个必要条件之一来防止死锁发生，如一次申请所有资源、剥夺资源等。",
        "core_elements": "破坏互斥条件 | 破坏占有等待 | 破坏不可剥夺 | 破坏循环等待",
        "key_terms": "死锁预防 | 资源一次性申请 | 资源剥夺",
        "formulas": "[]",
        "common_mistakes": "认为破坏互斥条件总是可行 | 忽略预防策略对资源利用率的影响",
        "scope_boundary": "不讨论预防策略的实际应用限制",
        "prerequisites_desc": "需理解死锁的四个必要条件。"
    },
    {
        "node_id": 770,
        "name": "2.4.3 死锁避免",
        "level": 4,
        "definition": "在资源分配时动态检查系统安全性，若分配后可能导致不安全状态则拒绝分配。",
        "core_elements": "安全状态 | 银行家算法 | 安全性检查 | 资源请求算法",
        "key_terms": "死锁避免 | 银行家算法 | 安全序列 | 安全状态",
        "formulas": "Need[i][j] = Max[i][j] - Allocation[i][j] | Available[j] >= Need[i][j]",
        "common_mistakes": "混淆安全状态和死锁状态 | 忽略安全性检查的开销",
        "scope_boundary": "不讨论银行家算法的时间复杂度优化",
        "prerequisites_desc": "需理解死锁的概念和必要条件。"
    },
    {
        "node_id": 771,
        "name": "2.4.4 死锁检测与解除",
        "level": 4,
        "definition": "允许死锁发生，通过检测算法发现死锁并采取措施解除，如终止进程或资源剥夺。",
        "core_elements": "检测算法 | 等待图 | 终止进程 | 资源剥夺",
        "key_terms": "死锁检测 | 终止进程 | 资源回收",
        "formulas": "[]",
        "common_mistakes": "忽略检测算法的定期执行 | 终止进程时选择不当",
        "scope_boundary": "不讨论检测算法的优化和开销",
        "prerequisites_desc": "需了解死锁的产生条件和预防避免方法。"
    },

    # Chapter 3 - 内存管理
    {
        "node_id": 772,
        "name": "3 内存管理",
        "level": 2,
        "definition": "操作系统对内存资源的分配、保护、扩充和回收的管理功能。",
        "core_elements": "内存分配 | 内存保护 | 内存扩充 | 地址映射",
        "key_terms": "内存管理 | 地址空间 | 虚拟内存 | 分页 | 分段",
        "formulas": "[]",
        "common_mistakes": "混淆物理地址和逻辑地址 | 忽略内存保护的重要性",
        "scope_boundary": "仅讨论单处理器系统的内存管理",
        "prerequisites_desc": "需了解计算机组成原理中的存储系统。"
    },
    {
        "node_id": 773,
        "name": "3.1 内存管理概念",
        "level": 3,
        "definition": "内存管理的基本原理和各种存储分配方式，包括连续分配、分页、分段和段页式管理。",
        "core_elements": "基本原理 | 连续分配 | 分页管理 | 分段管理 | 段页式",
        "key_terms": "内存管理 | 分配方式 | 地址映射",
        "formulas": "[]",
        "common_mistakes": "混淆不同分配方式的特点 | 忽略地址映射的重要性",
        "scope_boundary": "不讨论虚拟内存的具体实现",
        "prerequisites_desc": "需了解计算机内存结构和操作系统功能。"
    },
    {
        "node_id": 774,
        "name": "3.1.1 内存管理的基本原理和要求",
        "level": 4,
        "definition": "内存管理需实现内存的分配与回收、地址转换、内存保护和内存扩充等功能。",
        "core_elements": "分配与回收 | 地址转换 | 内存保护 | 内存扩充",
        "key_terms": "地址转换 | 内存保护 | 内存扩充",
        "formulas": "逻辑地址 + 基址寄存器 = 物理地址",
        "common_mistakes": "忽略内存保护机制 | 混淆静态和动态地址重定位",
        "scope_boundary": "不讨论具体分配算法的实现",
        "prerequisites_desc": "需了解计算机内存的基本结构。"
    },
    {
        "node_id": 775,
        "name": "3.1.2 连续分配管理方式",
        "level": 4,
        "definition": "为用户程序分配连续的内存空间，包括单一连续分配、固定分区和动态分区分配。",
        "core_elements": "单一连续分配 | 固定分区 | 动态分区 | 分配算法",
        "key_terms": "连续分配 | 分区分配 | 首次适应 | 最佳适应",
        "formulas": "[]",
        "common_mistakes": "忽略内部碎片和外部碎片的区别 | 低估动态分区分配的开销",
        "scope_boundary": "不讨论分页和分段等离散分配方式",
        "prerequisites_desc": "需了解内存管理的基本原理。"
    },
    {
        "node_id": 776,
        "name": "3.1.3 基本分页存储管理",
        "level": 4,
        "definition": "将进程的逻辑地址空间等分为页，物理内存等分为页框，通过页表实现逻辑地址到物理地址的映射。",
        "core_elements": "页 | 页框 | 页表 | 地址映射 | 快表",
        "key_terms": "分页 | 页表 | 快表TLB | 页号 | 页内偏移",
        "formulas": "逻辑地址 = 页号 + 页内偏移 | 物理地址 = 页框号 + 页内偏移",
        "common_mistakes": "忽略页表的内存开销 | 混淆页号和页框号",
        "scope_boundary": "不讨论多级页表和虚拟内存的实现",
        "prerequisites_desc": "需理解内存管理的基本原理和地址转换。"
    },
    {
        "node_id": 777,
        "name": "3.1.4 基本分段存储管理",
        "level": 4,
        "definition": "按照程序的逻辑结构将进程地址空间分为若干段，每段有独立的段表项进行地址映射。",
        "core_elements": "段 | 段表 | 段基址 | 段长 | 地址映射",
        "key_terms": "分段 | 段表 | 段基址 | 段长",
        "formulas": "物理地址 = 段基址 + 段内偏移",
        "common_mistakes": "混淆分段和分页的区别 | 忽略段长的检查",
        "scope_boundary": "不讨论段页式存储管理",
        "prerequisites_desc": "需了解分页存储管理的基本原理。"
    },
    {
        "node_id": 778,
        "name": "3.1.5 段页式存储管理",
        "level": 4,
        "definition": "先将进程分段，再将每段分页，结合分段和分页优点的存储管理方式。",
        "core_elements": "分段 | 分页 | 段表 | 页表 | 三级地址转换",
        "key_terms": "段页式 | 段表 | 页表 | 逻辑地址",
        "formulas": "逻辑地址 = 段号 + 页号 + 页内偏移",
        "common_mistakes": "忽略三次访存的性能开销 | 混淆段页式的地址结构",
        "scope_boundary": "不讨论段页式的具体优化技术",
        "prerequisites_desc": "需分别掌握分段和分页存储管理。"
    },
    {
        "node_id": 779,
        "name": "3.2 虚拟内存管理",
        "level": 3,
        "definition": "通过请求调页和页面置换技术，使进程的逻辑地址空间可以大于物理内存空间。",
        "core_elements": "虚拟内存 | 请求分页 | 页面置换 | 内存分配",
        "key_terms": "虚拟内存 | 请求分页 | 页面置换 | 抖动",
        "formulas": "[]",
        "common_mistakes": "认为虚拟内存就是磁盘空间 | 忽略页面置换算法的影响",
        "scope_boundary": "不讨论虚拟内存的硬件实现细节",
        "prerequisites_desc": "需掌握基本分页存储管理的原理。"
    },
    {
        "node_id": 780,
        "name": "3.2.1 虚拟内存的基本概念",
        "level": 4,
        "definition": "虚拟内存利用局部性原理，将部分页面驻留内存，其余驻留外存，实现逻辑地址空间大于物理内存。",
        "core_elements": "局部性原理 | 请求调页 | 缺页中断 | 工作集",
        "key_terms": "虚拟内存 | 局部性原理 | 缺页中断",
        "formulas": "[]",
        "common_mistakes": "忽略局部性原理的重要性 | 认为虚拟内存是无限的",
        "scope_boundary": "不讨论虚拟内存的具体实现技术",
        "prerequisites_desc": "需理解分页存储管理的基本原理。"
    },
    {
        "node_id": 781,
        "name": "3.2.2 请求分页管理方式",
        "level": 4,
        "definition": "在基本分页基础上增加请求功能，仅装入部分页面即可执行，需要时再调入其他页面。",
        "core_elements": "页表项修改 | 缺页中断 | 页面调入 | 页面调出",
        "key_terms": "请求分页 | 缺页中断 | 页面调入",
        "formulas": "缺页率 = 缺页次数 / 访问页面次数",
        "common_mistakes": "忽略页表项中状态位的作用 | 低估缺页中断的处理开销",
        "scope_boundary": "不讨论具体的页面置换算法",
        "prerequisites_desc": "需掌握基本分页存储管理的原理。"
    },
    {
        "node_id": 782,
        "name": "3.2.3 页框分配",
        "level": 4,
        "definition": "操作系统为进程分配物理页框的策略，包括固定分配和可变分配，以及局部置换和全局置换。",
        "core_elements": "固定分配 | 可变分配 | 局部置换 | 全局置换",
        "key_terms": "页框分配 | 固定分配 | 可变分配",
        "formulas": "[]",
        "common_mistakes": "混淆固定分配和可变分配的区别 | 忽略置换范围的影响",
        "scope_boundary": "不讨论页框分配的具体算法实现",
        "prerequisites_desc": "需理解请求分页的基本原理。"
    },
    {
        "node_id": 783,
        "name": "3.2.4 页面置换算法",
        "level": 4,
        "definition": "当内存不足时选择哪个页面调出的算法，包括OPT、FIFO、LRU、Clock等算法。",
        "core_elements": "OPT | FIFO | LRU | Clock | 最近最少使用",
        "key_terms": "页面置换 | 最佳置换 | 先进先出 | 最近最久未使用",
        "formulas": "缺页中断次数 / 访问次数 = 缺页率",
        "common_mistakes": "混淆LRU和FIFO的性能 | 忽略Belady异常现象",
        "scope_boundary": "不讨论各算法的硬件实现",
        "prerequisites_desc": "需掌握请求分页和缺页中断的概念。"
    },
    {
        "node_id": 784,
        "name": "3.2.5 抖动和工作集",
        "level": 4,
        "definition": "抖动是因分配给进程的页框过少导致频繁缺页的现象，工作集是进程在一段时间内访问的页面集合。",
        "core_elements": "抖动 | 工作集 | 驻留集 | 缺页率",
        "key_terms": "抖动 | 工作集 | 驻留集",
        "formulas": "工作集 W(t, Δ) = {在t-Δ到t时间内访问的页面集合}",
        "common_mistakes": "将抖动等同于缺页中断 | 忽略工作集模型的作用",
        "scope_boundary": "不讨论抖动检测的具体算法",
        "prerequisites_desc": "需理解页面置换和缺页中断的概念。"
    },
    {
        "node_id": 785,
        "name": "3.2.6 页框回收",
        "level": 4,
        "definition": "当可用内存不足时，操作系统选择合适的页面写回磁盘以释放内存空间的过程。",
        "core_elements": "脏页写回 | 干净页释放 | 回收策略 | LRU算法",
        "key_terms": "页框回收 | 脏页 | 干净页",
        "formulas": "[]",
        "common_mistakes": "忽略脏页和干净页的处理差异 | 低估回收操作的开销",
        "scope_boundary": "不讨论页框回收的具体实现细节",
        "prerequisites_desc": "需了解页面置换算法和内存管理。"
    },
    {
        "node_id": 786,
        "name": "3.2.7 内存映射文件",
        "level": 4,
        "definition": "将文件直接映射到进程的虚拟地址空间，使文件访问像内存访问一样简单高效。",
        "core_elements": "文件映射 | 虚拟地址 | 按需调页 | 延迟写回",
        "key_terms": "内存映射文件 | mmap | 文件映射",
        "formulas": "[]",
        "common_mistakes": "认为内存映射文件会立即加载整个文件 | 混淆内存映射和普通文件I/O",
        "scope_boundary": "不讨论内存映射文件的系统调用实现",
        "prerequisites_desc": "需了解虚拟内存和文件系统的基本概念。"
    },
    {
        "node_id": 787,
        "name": "3.2.8 虚拟存储器性能影响因素",
        "level": 3,
        "definition": "影响虚拟存储器性能的因素包括页大小、页框数、置换算法、局部性程度和磁盘速度等。",
        "core_elements": "页大小 | 页框数 | 置换算法 | 局部性 | 磁盘速度",
        "key_terms": "性能因素 | 页大小 | 置换算法",
        "formulas": "有效访问时间 = (1-缺页率)×内存访问时间 + 缺页率×缺页中断处理时间",
        "common_mistakes": "忽略页大小对性能的影响 | 认为增加页框数总能改善性能",
        "scope_boundary": "不讨论性能优化的具体技术手段",
        "prerequisites_desc": "需掌握虚拟内存和页面置换算法。"
    },
    {
        "node_id": 788,
        "name": "3.2.9 地址翻译的示例",
        "level": 3,
        "definition": "通过具体例子演示分页或分段系统中逻辑地址到物理地址的转换过程。",
        "core_elements": "地址结构 | 页表查找 | 物理地址计算 | 快表使用",
        "key_terms": "地址翻译 | 逻辑地址 | 物理地址 | 页表",
        "formulas": "物理地址 = 页框号 × 页大小 + 页内偏移",
        "common_mistakes": "地址计算时单位换算错误 | 忽略快表命中情况",
        "scope_boundary": "不讨论复杂的多级地址翻译",
        "prerequisites_desc": "需掌握分页存储管理的地址映射方法。"
    },

    # Chapter 4 - 文件管理
    {
        "node_id": 789,
        "name": "4 文件管理",
        "level": 2,
        "definition": "操作系统对文件的组织、存储、检索、共享和保护的管理功能。",
        "core_elements": "文件系统 | 目录管理 | 文件存储 | 文件共享",
        "key_terms": "文件 | 目录 | 文件系统 | 文件控制块",
        "formulas": "[]",
        "common_mistakes": "混淆文件的逻辑结构和物理结构 | 忽略文件保护的重要性",
        "scope_boundary": "仅讨论文件系统的基本原理",
        "prerequisites_desc": "需了解操作系统的基本概念和存储管理。"
    },
    {
        "node_id": 790,
        "name": "4.1 文件系统基础",
        "level": 3,
        "definition": "文件系统的基础概念，包括文件的定义、结构、属性和操作等。",
        "core_elements": "文件定义 | 文件结构 | 文件属性 | 文件操作",
        "key_terms": "文件 | 文件系统 | 文件属性",
        "formulas": "[]",
        "common_mistakes": "混淆文件的不同结构类型 | 忽略文件系统层次结构",
        "scope_boundary": "不讨论具体文件系统的实现",
        "prerequisites_desc": "需了解操作系统的基本概念和存储管理。"
    },
    {
        "node_id": 791,
        "name": "4.1.1 文件的基本概念",
        "level": 4,
        "definition": "文件是具有文件名的一组相关信息的集合，是操作系统中信息存储的基本单位。",
        "core_elements": "文件名 | 文件内容 | 文件属性 | 文件类型",
        "key_terms": "文件 | 文件名 | 文件属性 | 文件类型",
        "formulas": "[]",
        "common_mistakes": "认为文件名就是文件的全部 | 忽略文件属性的重要性",
        "scope_boundary": "不讨论文件系统的具体实现",
        "prerequisites_desc": "需了解信息存储和文件系统的基本概念。"
    },
    {
        "node_id": 792,
        "name": "4.1.2 文件系统结构",
        "level": 4,
        "definition": "文件系统的层次结构，从用户接口到物理存储的多层抽象设计。",
        "core_elements": "用户接口 | 逻辑文件系统 | 文件组织模块 | 基本文件系统",
        "key_terms": "文件系统 | 层次结构 | 抽象层",
        "formulas": "[]",
        "common_mistakes": "混淆各层次的功能 | 忽略层次间接口的定义",
        "scope_boundary": "不讨论各层次的具体实现细节",
        "prerequisites_desc": "需了解文件的基本概念和操作系统的层次结构。"
    },
    {
        "node_id": 793,
        "name": "4.1.3 文件的逻辑结构",
        "level": 4,
        "definition": "文件的逻辑结构包括无结构文件（流式文件）和有结构文件（记录式文件）两种类型。",
        "core_elements": "无结构文件 | 有结构文件 | 流式文件 | 记录式文件",
        "key_terms": "逻辑结构 | 流式文件 | 记录式文件",
        "formulas": "[]",
        "common_mistakes": "混淆逻辑结构和物理结构 | 忽略流式文件的特点",
        "scope_boundary": "不讨论文件的物理存储结构",
        "prerequisites_desc": "需了解文件的基本概念和组织方式。"
    },
    {
        "node_id": 794,
        "name": "4.2 目录与文件",
        "level": 3,
        "definition": "目录用于组织和管理文件，文件控制块记录文件的元数据信息。",
        "core_elements": "目录结构 | 文件控制块 | 索引节点 | 文件操作",
        "key_terms": "目录 | 文件控制块 | 索引节点 | inode",
        "formulas": "[]",
        "common_mistakes": "混淆目录和文件的概念 | 忽略索引节点的作用",
        "scope_boundary": "不讨论目录的具体实现算法",
        "prerequisites_desc": "需了解文件系统的基本概念。"
    },
    {
        "node_id": 795,
        "name": "4.2.1 目录的基本概念",
        "level": 4,
        "definition": "目录是文件系统中用于组织和管理文件的特殊文件，记录了文件名到文件控制块的映射。",
        "core_elements": "文件名映射 | 文件组织 | 目录项 | 路径名",
        "key_terms": "目录 | 目录项 | 路径名 | 绝对路径",
        "formulas": "[]",
        "common_mistakes": "认为目录就是文件夹 | 忽略目录的组织功能",
        "scope_boundary": "不讨论目录的具体实现方式",
        "prerequisites_desc": "需了解文件的基本概念和组织方式。"
    },
    {
        "node_id": 796,
        "name": "4.2.2 文件控制块和索引节点",
        "level": 4,
        "definition": "文件控制块(FCB)包含文件的所有属性信息，索引节点(inode)将文件描述信息从目录项中分离。",
        "core_elements": "文件控制块 | 索引节点 | 文件属性 | 目录项",
        "key_terms": "FCB | 索引节点 | inode | 目录项",
        "formulas": "[]",
        "common_mistakes": "混淆FCB和索引节点的区别 | 忽略索引节点对目录查询的优化",
        "scope_boundary": "不讨论索引节点的具体数据结构",
        "prerequisites_desc": "需了解目录的基本概念和文件属性。"
    },
    {
        "node_id": 797,
        "name": "4.2.3 目录结构",
        "level": 4,
        "definition": "目录的组织方式，包括单级目录、两级目录、树形目录和图形目录结构等。",
        "core_elements": "单级目录 | 两级目录 | 树形目录 | 图形目录",
        "key_terms": "目录结构 | 树形目录 | 图形目录",
        "formulas": "[]",
        "common_mistakes": "混淆不同目录结构的特点 | 忽略树形目录的层次限制",
        "scope_boundary": "不讨论目录结构的具体实现",
        "prerequisites_desc": "需了解目录的基本概念和功能。"
    },
    {
        "node_id": 798,
        "name": "4.2.4 目录的操作",
        "level": 4,
        "definition": "目录的基本操作包括创建、删除、重命名、列出内容和查找文件等。",
        "core_elements": "创建目录 | 删除目录 | 重命名 | 查找文件",
        "key_terms": "目录操作 | 创建 | 删除 | 查找",
        "formulas": "[]",
        "common_mistakes": "忽略目录操作的权限检查 | 低估目录遍历的开销",
        "scope_boundary": "不讨论目录操作的并发控制",
        "prerequisites_desc": "需了解目录的基本结构和文件操作。"
    },
    {
        "node_id": 799,
        "name": "4.2.5 目录实现",
        "level": 4,
        "definition": "目录的实现方式包括线性列表和哈希表两种，各有优缺点和适用场景。",
        "core_elements": "线性列表 | 哈希表 | 查找效率 | 存储开销",
        "key_terms": "目录实现 | 线性列表 | 哈希表",
        "formulas": "[]",
        "common_mistakes": "忽略哈希表的冲突处理 | 低估目录大小对查找的影响",
        "scope_boundary": "不讨论目录实现的优化技术",
        "prerequisites_desc": "需了解目录的基本操作和数据结构。"
    },
    {
        "node_id": 800,
        "name": "4.2.6 文件的物理结构",
        "level": 4,
        "definition": "文件在外存中的存储方式，包括连续分配、链接分配和索引分配三种方式。",
        "core_elements": "连续分配 | 链接分配 | 索引分配 | 文件块",
        "key_terms": "物理结构 | 连续分配 | 链接分配 | 索引分配",
        "formulas": "[]",
        "common_mistakes": "混淆三种分配方式的特点 | 忽略碎片问题",
        "scope_boundary": "不讨论具体分配方式的实现细节",
        "prerequisites_desc": "需了解文件的逻辑结构和存储管理。"
    },
    {
        "node_id": 801,
        "name": "4.2.7 文件的操作",
        "level": 4,
        "definition": "文件的基本操作包括创建、删除、读、写、重定位、打开和关闭等。",
        "core_elements": "创建 | 删除 | 读 | 写 | 打开 | 关闭",
        "key_terms": "文件操作 | create | delete | open | close",
        "formulas": "[]",
        "common_mistakes": "忽略文件打开的系统开销 | 不关闭已打开文件导致资源泄漏",
        "scope_boundary": "不讨论文件操作的具体系统调用实现",
        "prerequisites_desc": "需了解文件的基本概念和目录结构。"
    },
    {
        "node_id": 802,
        "name": "4.2.8 文件共享",
        "level": 4,
        "definition": "多个用户或进程可以同时访问同一文件的机制，包括硬链接和软链接两种方式。",
        "core_elements": "硬链接 | 软链接 | 索引节点共享 | 访问控制",
        "key_terms": "文件共享 | 硬链接 | 软链接 | 符号链接",
        "formulas": "[]",
        "common_mistakes": "混淆硬链接和软链接的区别 | 忽略文件共享的权限控制",
        "scope_boundary": "不讨论文件共享的安全性问题",
        "prerequisites_desc": "需了解文件控制块和索引节点的概念。"
    },
    {
        "node_id": 803,
        "name": "4.2.9 文件保护",
        "level": 4,
        "definition": "保护文件免受未授权访问和误操作的机制，包括访问控制列表和权限位等方式。",
        "core_elements": "访问控制列表 | 权限位 | 用户组 | 口令保护",
        "key_terms": "文件保护 | 访问控制 | 权限位",
        "formulas": "[]",
        "common_mistakes": "忽略文件保护的重要性 | 低估权限设置的复杂性",
        "scope_boundary": "不讨论文件加密和安全审计",
        "prerequisites_desc": "需了解文件共享和访问控制的基本概念。"
    },
    {
        "node_id": 804,
        "name": "4.3 文件系统",
        "level": 3,
        "definition": "文件系统的整体组织、存储空间管理和虚拟文件系统等概念。",
        "core_elements": "文件系统布局 | 存储空间管理 | 虚拟文件系统 | 挂载",
        "key_terms": "文件系统 | 存储空间 | 虚拟文件系统 | 挂载",
        "formulas": "[]",
        "common_mistakes": "混淆文件系统和文件的概念 | 忽略虚拟文件系统的作用",
        "scope_boundary": "不讨论具体文件系统的实现",
        "prerequisites_desc": "需了解文件和目录的基本概念。"
    },
    {
        "node_id": 805,
        "name": "4.3.1 文件系统布局",
        "level": 4,
        "definition": "文件系统在磁盘上的组织结构，包括引导块、超级块、空闲空间管理、根目录和数据区等。",
        "core_elements": "引导块 | 超级块 | 空闲空间管理 | 根目录 | 数据区",
        "key_terms": "文件系统布局 | 引导块 | 超级块",
        "formulas": "[]",
        "common_mistakes": "忽略引导块的重要性 | 混淆超级块和根目录",
        "scope_boundary": "不讨论各区域的具体实现",
        "prerequisites_desc": "需了解文件系统的基本结构。"
    },
    {
        "node_id": 806,
        "name": "4.3.2 文件存储空间管理",
        "level": 4,
        "definition": "操作系统管理文件存储空间的方法，包括空闲表法、空闲链表法、位示图法和成组链接法。",
        "core_elements": "空闲表法 | 空闲链表法 | 位示图法 | 成组链接法",
        "key_terms": "空闲空间管理 | 位示图 | 空闲链表",
        "formulas": "[]",
        "common_mistakes": "混淆各种管理方法的特点 | 忽略分配算法的选择",
        "scope_boundary": "不讨论具体管理方法的实现细节",
        "prerequisites_desc": "需了解文件系统的存储结构。"
    },
    {
        "node_id": 807,
        "name": "4.3.3 虚拟文件系统",
        "level": 4,
        "definition": "虚拟文件系统(VFS)为用户提供统一的文件系统接口，屏蔽不同文件系统的实现差异。",
        "core_elements": "统一接口 | 文件系统类型 | 挂载点 | 缓存机制",
        "key_terms": "VFS | 虚拟文件系统 | 挂载点",
        "formulas": "[]",
        "common_mistakes": "将虚拟文件系统等同于虚拟内存 | 忽略VFS的抽象作用",
        "scope_boundary": "不讨论VFS的具体实现细节",
        "prerequisites_desc": "需了解文件系统的整体结构和概念。"
    },
    {
        "node_id": 808,
        "name": "4.3.4 文件系统挂载",
        "level": 4,
        "definition": "将一个文件系统的根目录连接到系统目录树的某个节点上，使其可以被访问。",
        "core_elements": "挂载点 | 挂载操作 | 卸载操作 | 自动挂载",
        "key_terms": "挂载 | 挂载点 | 卸载",
        "formulas": "[]",
        "common_mistakes": "混淆挂载和安装的概念 | 忽略卸载操作的重要性",
        "scope_boundary": "不讨论挂载的具体实现机制",
        "prerequisites_desc": "需了解文件系统和目录树的概念。"
    },

    # Chapter 5 - I/O管理
    {
        "node_id": 809,
        "name": "5 I/O管理",
        "level": 2,
        "definition": "操作系统对输入输出设备的管理，包括设备管理、缓冲管理和磁盘管理等。",
        "core_elements": "设备管理 | I/O控制 | 缓冲管理 | 磁盘管理",
        "key_terms": "I/O管理 | 设备驱动 | 缓冲区 | 磁盘调度",
        "formulas": "[]",
        "common_mistakes": "忽略I/O操作的复杂性 | 混淆设备驱动和设备管理",
        "scope_boundary": "仅讨论I/O管理的基本原理",
        "prerequisites_desc": "需了解计算机组成原理和操作系统基本概念。"
    },
    {
        "node_id": 810,
        "name": "5.1 I/O管理概述",
        "level": 3,
        "definition": "I/O设备的分类、控制方式和I/O软件的层次结构概述。",
        "core_elements": "设备分类 | I/O控制方式 | 软件层次 | 接口设计",
        "key_terms": "I/O设备 | 控制方式 | 软件层次",
        "formulas": "[]",
        "common_mistakes": "混淆不同I/O控制方式的特点 | 忽略I/O软件层次的作用",
        "scope_boundary": "不讨论具体设备的控制细节",
        "prerequisites_desc": "需了解计算机组成原理和操作系统功能。"
    },
    {
        "node_id": 811,
        "name": "5.1.1 I/O设备",
        "level": 4,
        "definition": "I/O设备是计算机与外部世界交互的硬件设备，按数据传输单位分为块设备和字符设备。",
        "core_elements": "块设备 | 字符设备 | 网络设备 | 设备控制器",
        "key_terms": "块设备 | 字符设备 | 设备控制器",
        "formulas": "[]",
        "common_mistakes": "混淆块设备和字符设备的区别 | 忽略设备控制器的作用",
        "scope_boundary": "不讨论具体设备的工作原理",
        "prerequisites_desc": "需了解计算机硬件组成和I/O系统。"
    },
    {
        "node_id": 812,
        "name": "5.1.2 I/O控制方式",
        "level": 4,
        "definition": "CPU与设备之间的数据传输控制方式，包括程序直接控制、中断驱动、DMA和通道控制。",
        "core_elements": "程序直接控制 | 中断驱动 | DMA | 通道控制",
        "key_terms": "I/O控制 | 程序查询 | 中断驱动 | DMA | 通道",
        "formulas": "[]",
        "common_mistakes": "混淆四种控制方式的区别 | 低估DMA和通道的效率优势",
        "scope_boundary": "不讨论各控制方式的硬件实现细节",
        "prerequisites_desc": "需了解计算机组成原理和I/O设备。"
    },
    {
        "node_id": 813,
        "name": "5.1.3 I/O软件层次结构",
        "level": 4,
        "definition": "I/O软件从用户层到硬件层的层次化设计，每层提供不同级别的抽象和功能。",
        "core_elements": "用户层I/O软件 | 设备独立性软件 | 设备驱动程序 | 中断处理程序",
        "key_terms": "I/O软件层次 | 用户层 | 设备独立性软件",
        "formulas": "[]",
        "common_mistakes": "混淆各层次的功能边界 | 忽略层次化设计的优势",
        "scope_boundary": "不讨论各层次的具体实现",
        "prerequisites_desc": "需了解操作系统和I/O设备的基本概念。"
    },
    {
        "node_id": 814,
        "name": "5.1.4 应用程序I/O接口",
        "level": 4,
        "definition": "操作系统提供给应用程序的I/O接口类型，包括阻塞、非阻塞、同步和异步等接口。",
        "core_elements": "阻塞I/O | 非阻塞I/O | 同步I/O | 异步I/O",
        "key_terms": "I/O接口 | 阻塞I/O | 非阻塞I/O | 异步I/O",
        "formulas": "[]",
        "common_mistakes": "混淆同步和异步I/O的区别 | 忽略阻塞I/O的性能影响",
        "scope_boundary": "不讨论具体I/O接口的实现",
        "prerequisites_desc": "需了解I/O软件层次和设备控制方式。"
    },
    {
        "node_id": 815,
        "name": "5.2 设备独立性软件",
        "level": 3,
        "definition": "实现设备独立性的软件层，提供统一的设备访问接口和通用功能。",
        "core_elements": "设备独立性 | 缓冲管理 | 设备分配 | SPOOLing",
        "key_terms": "设备独立性软件 | 缓冲 | 设备分配 | SPOOLing",
        "formulas": "[]",
        "common_mistakes": "混淆设备独立性和设备无关性 | 忽略缓冲管理的作用",
        "scope_boundary": "不讨论具体设备驱动程序的实现",
        "prerequisites_desc": "需了解I/O软件层次结构和设备分类。"
    },
    {
        "node_id": 816,
        "name": "5.2.1 设备独立性软件",
        "level": 4,
        "definition": "设备独立性软件提供统一的设备命名、保护、缓冲管理和设备分配与释放等功能。",
        "core_elements": "统一命名 | 设备保护 | 缓冲管理 | 设备分配",
        "key_terms": "设备独立性 | 统一命名 | 缓冲管理",
        "formulas": "[]",
        "common_mistakes": "忽略设备独立性的重要性 | 低估缓冲管理的复杂性",
        "scope_boundary": "不讨论设备独立性的具体实现技术",
        "prerequisites_desc": "需了解I/O软件层次和设备管理概念。"
    },
    {
        "node_id": 817,
        "name": "5.2.2 高速缓存与缓冲区",
        "level": 4,
        "definition": "缓冲区是内存中用于暂存I/O数据的区域，高速缓存用于提高频繁访问数据的速度。",
        "core_elements": "缓冲区 | 高速缓存 | 单缓冲 | 双缓冲 | 循环缓冲",
        "key_terms": "缓冲区 | 高速缓存 | 单缓冲 | 双缓冲",
        "formulas": "[]",
        "common_mistakes": "混淆缓冲和高速缓存的概念 | 忽略缓冲区大小对性能的影响",
        "scope_boundary": "不讨论缓冲区的具体实现算法",
        "prerequisites_desc": "需了解I/O设备和内存管理的基本概念。"
    },
    {
        "node_id": 818,
        "name": "5.2.3 设备分配与回收",
        "level": 4,
        "definition": "操作系统根据一定策略将I/O设备分配给请求进程，使用完毕后回收设备。",
        "core_elements": "分配策略 | 回收机制 | 设备控制表 | 分配算法",
        "key_terms": "设备分配 | 设备回收 | 设备控制表",
        "formulas": "[]",
        "common_mistakes": "忽略设备分配的安全性 | 低估设备回收的复杂性",
        "scope_boundary": "不讨论设备分配的具体算法实现",
        "prerequisites_desc": "需了解设备独立性和缓冲管理。"
    },
    {
        "node_id": 819,
        "name": "5.2.4 SPOOLing技术（假脱机技术）",
        "level": 4,
        "definition": "将独占设备改造为共享设备的技术，通过在外存设置缓冲区模拟脱机输入输出。",
        "core_elements": "假脱机输入 | 假脱机输出 | 设备共享 | 独占设备改造",
        "key_terms": "SPOOLing | 假脱机 | 输入井 | 输出井",
        "formulas": "[]",
        "common_mistakes": "将SPOOLing等同于假脱机打印 | 忽略SPOOLing的资源共享本质",
        "scope_boundary": "不讨论SPOOLing的具体实现细节",
        "prerequisites_desc": "需了解设备分配和独占设备的特点。"
    },
    {
        "node_id": 820,
        "name": "5.2.5 设备驱动程序接口",
        "level": 4,
        "definition": "操作系统与设备驱动程序之间的标准接口，规定了驱动程序必须实现的函数集合。",
        "core_elements": "初始化函数 | 读写函数 | 控制函数 | 中断处理",
        "key_terms": "设备驱动接口 | 初始化 | 读写操作 | 中断处理",
        "formulas": "[]",
        "common_mistakes": "忽略驱动程序接口的标准化要求 | 混淆驱动程序和应用程序",
        "scope_boundary": "不讨论具体驱动程序的实现",
        "prerequisites_desc": "需了解I/O软件层次和设备控制方式。"
    },
    {
        "node_id": 821,
        "name": "5.2.6 I/O操作举例",
        "level": 3,
        "definition": "通过具体I/O操作实例说明操作系统管理I/O设备的工作过程。",
        "core_elements": "读操作流程 | 写操作流程 | 控制操作流程 | 缓冲处理",
        "key_terms": "I/O操作 | 读操作 | 写操作 | 缓冲处理",
        "formulas": "[]",
        "common_mistakes": "忽略I/O操作的错误处理 | 低估I/O操作的延迟",
        "scope_boundary": "不讨论具体设备的I/O操作细节",
        "prerequisites_desc": "需了解I/O管理的基本原理和层次结构。"
    },
    {
        "node_id": 822,
        "name": "5.3 磁盘和固态硬盘",
        "level": 3,
        "definition": "磁盘和固态硬盘的结构、管理方式和调度算法。",
        "core_elements": "磁盘结构 | 磁盘管理 | 调度算法 | 固态硬盘",
        "key_terms": "磁盘 | 固态硬盘 | 磁盘调度 | 寻道时间",
        "formulas": "[]",
        "common_mistakes": "混淆磁盘和固态硬盘的工作原理 | 忽略磁盘调度的重要性",
        "scope_boundary": "不讨论磁盘和固态硬盘的硬件实现",
        "prerequisites_desc": "需了解I/O设备和设备管理的基本概念。"
    },
    {
        "node_id": 823,
        "name": "5.3.1 磁盘",
        "level": 4,
        "definition": "磁盘是由多个盘片组成的机械存储设备，数据存储在盘片的磁道和扇区中。",
        "core_elements": "盘片 | 磁道 | 扇区 | 磁头 | 寻道时间",
        "key_terms": "磁盘 | 磁道 | 扇区 | 寻道时间",
        "formulas": "访问时间 = 寻道时间 + 旋转延迟 + 传输时间",
        "common_mistakes": "忽略寻道时间对性能的影响 | 混淆磁道和扇区的概念",
        "scope_boundary": "不讨论磁盘的物理结构和工作原理",
        "prerequisites_desc": "需了解存储设备的基本分类。"
    },
    {
        "node_id": 824,
        "name": "5.3.2 磁盘的管理",
        "level": 4,
        "definition": "磁盘空间管理、磁盘格式化、坏块处理和磁盘冗余阵列(RAID)等管理功能。",
        "core_elements": "磁盘格式化 | 坏块处理 | 磁盘空间管理 | RAID",
        "key_terms": "磁盘管理 | 格式化 | 坏块 | RAID",
        "formulas": "[]",
        "common_mistakes": "忽略坏块处理的重要性 | 低估RAID的复杂性",
        "scope_boundary": "不讨论RAID级别的详细比较",
        "prerequisites_desc": "需了解磁盘的基本结构和存储方式。"
    },
    {
        "node_id": 825,
        "name": "5.3.3 磁盘调度算法",
        "level": 4,
        "definition": "磁盘调度算法决定多个I/O请求的服务顺序，包括FCFS、SSTF、SCAN、C-SCAN等算法。",
        "core_elements": "FCFS | SSTF | SCAN | C-SCAN | LOOK",
        "key_terms": "磁盘调度 | 最短寻道时间优先 | 扫描算法 | 循环扫描",
        "formulas": "平均寻道长度 = Σ寻道长度 / 请求数",
        "common_mistakes": "混淆不同磁盘调度算法的特点 | 忽略算法的公平性问题",
        "scope_boundary": "不讨论算法的具体实现代码",
        "prerequisites_desc": "需了解磁盘的结构和访问时间。"
    },
    {
        "node_id": 826,
        "name": "5.3.4 固态硬盘",
        "level": 4,
        "definition": "基于闪存技术的存储设备，具有速度快、无机械部件、能耗低等特点，但有写入次数限制。",
        "core_elements": "闪存技术 | 无机械部件 | 读写不对称 | 写入次数限制",
        "key_terms": "固态硬盘 | SSD | 闪存 | 磨损均衡",
        "formulas": "[]",
        "common_mistakes": "认为固态硬盘无限制的写入次数 | 忽略写入放大的影响",
        "scope_boundary": "不讨论固态硬盘的内部实现细节",
        "prerequisites_desc": "需了解磁盘的工作原理和存储技术。"
    },
]

# Write CSV
output_path = r"C:\creategame\AI学\docs\params_csv\os_all.csv"
with open(output_path, 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerow(["node_id", "name", "level", "definition", "core_elements", "key_terms", "formulas", "common_mistakes", "scope_boundary", "prerequisites_desc"])
    for row in rows:
        writer.writerow([
            row["node_id"],
            row["name"],
            row["level"],
            row["definition"],
            row["core_elements"],
            row["key_terms"],
            row["formulas"],
            row["common_mistakes"],
            row["scope_boundary"],
            row["prerequisites_desc"]
        ])

print(f"Written {len(rows)} rows to {output_path}")
